// <auto-generated />
namespace SmartAdminMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class timentry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(timentry));
        
        string IMigrationMetadata.Id
        {
            get { return "201711081520050_timentry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
